
project_id = "jqueiogjlyxkmlpgpiwv"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
port = 54323

[functions.create-booking]
verify_jwt = true

[functions.create-booking.import_map]
imports = {}

[functions.service-logging]
verify_jwt = true

[functions.service-logging.import_map]
imports = {}
